import { faker } from '@faker-js/faker'
import { Attachment, linkAttachment } from './attachments'

export type Person = {
  firstName: string
  lastName: string
  age: number
  visits: number
  progress: number
  salary: number
  status: 'relationship' | 'complicated' | 'single'
  avatar: Attachment | null
  attachment: Attachment | null
  subRows?: Person[]
}

const range = (len: number) => {
  const arr: number[] = []
  for (let i = 0; i < len; i++) {
    arr.push(i)
  }
  return arr
}

const AVATAR_COLORS = [
  '#2563eb',
  '#0891b2',
  '#059669',
  '#d97706',
  '#dc2626',
  '#7c3aed',
  '#db2777',
]

// Seeded avatars are inline SVG data URLs rather than remote placeholders: the
// app carries no network guarantee, and a data URL can never 404. The cell
// still handles onError, which is what covers uploaded blobs and any URL that
// really does fail.
const svgAvatar = (initials: string, color: string) => {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160">` +
    `<rect width="160" height="160" fill="${color}"/>` +
    `<text x="80" y="80" fill="#ffffff" font-family="sans-serif" font-size="68"` +
    ` text-anchor="middle" dominant-baseline="central">${initials}</text>` +
    `</svg>`
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
}

const textFile = (body: string) =>
  `data:text/plain;charset=utf-8,${encodeURIComponent(body)}`

const csvFile = (body: string) =>
  `data:text/csv;charset=utf-8,${encodeURIComponent(body)}`

const newPerson = (): Person => {
  const firstName = faker.person.firstName()
  const lastName = faker.person.lastName()
  const initials = `${firstName[0] ?? '?'}${lastName[0] ?? ''}`
  const color = faker.helpers.arrayElement(AVATAR_COLORS)

  // A quarter of the rows start empty so the upload affordance is visible.
  const avatar =
    faker.number.int(3) === 0
      ? null
      : linkAttachment(
          `${firstName}-${lastName}.svg`.toLowerCase(),
          'image/svg+xml',
          svgAvatar(initials, color),
        )

  const attachmentKind = faker.number.int(2)
  const notes = `Notes for ${firstName} ${lastName}\nGenerated by makeData.`
  const csv = `first,last\n${firstName},${lastName}\n`
  const attachment =
    attachmentKind === 0
      ? null
      : attachmentKind === 1
        ? linkAttachment(
            `${lastName}-notes.txt`.toLowerCase(),
            'text/plain',
            textFile(notes),
            notes.length,
          )
        : linkAttachment(
            `${lastName}-export.csv`.toLowerCase(),
            'text/csv',
            csvFile(csv),
            csv.length,
          )

  return {
    firstName,
    lastName,
    age: faker.number.int(40),
    visits: faker.number.int(1000),
    progress: faker.number.int(100),
    salary: faker.number.int({ min: 32000, max: 240000 }) +
      faker.number.int(99) / 100,
    status: faker.helpers.shuffle<Person['status']>([
      'relationship',
      'complicated',
      'single',
    ])[0]!,
    avatar,
    attachment,
  }
}

export function makeData(...lens: number[]) {
  const makeDataLevel = (depth = 0): Person[] => {
    const len = lens[depth]!
    return range(len).map((): Person => {
      return {
        ...newPerson(),
        subRows: lens[depth + 1] ? makeDataLevel(depth + 1) : undefined,
      }
    })
  }

  return makeDataLevel()
}
